---
title: "Untitled"
author: "Dilpreet Singh"
date: "6/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 4 - Computing global autocorrelation for top 3 problems

```{r}
# add count of problems column to ward boundaries
ward_boundaries_1 <- ward_boundaries
count_1 <- c(695,888,821,859,1832,781,1385,1112,1784,693)
ward_boundaries_1$count <- count_1
ward_boundaries_1
```

```{r}
# convert ward_boundaries to sp object
ward_boundaries_1_sp <- as_Spatial(ward_boundaries_1)
```

```{r}
# univariate analysis
# map the count of problems distribution using a quantile classification scheme
library(tmap)
tm_shape(ward_boundaries_1_sp) + tm_polygons(style="quantile", col = "count") +
  tm_legend(outside = TRUE, text.size = .8) 
```
```{r}
ward_boundaries_1_sp$WARD[1]
```

```{r}
# finding neighboring polygons
nb <- poly2nb(ward_boundaries_1_sp, queen=TRUE)
```

```{r}
# neighbours of ward 9
nb[[1]]
```
```{r}
#neighbor names
ward_boundaries_1_sp$WARD[c(3,4,6,8,10)]

```


```{r}
# Assign weights to each neighboring polygon
lw <- nb2listw(nb, style="W", zero.policy=TRUE)
```


```{r}
# compute the average count value for each polygon
count.lag <- lag.listw(lw, ward_boundaries_1_sp$count)
```

```{r}
# moran 1 is 0.174, very low, there is randomness
moran.test(ward_boundaries_1_sp$count,lw)
```

```{r}
MC<- moran.mc(ward_boundaries_1_sp$count, lw, nsim=599)
MC
```

```{r}
plot(MC, main="", las=1)
```

```{r}
# Problem 1
ward_boundaries_2 <- ward_boundaries

count_1 <- c(69,98,76,135,528,142,344,197,336,79)
ward_boundaries_2$count <- count_1

ward_boundaries_sp_2 <- as_Spatial(ward_boundaries_2)

#neighbors
nb <- poly2nb(ward_boundaries_sp_2, queen=TRUE)

#weights
lw <- nb2listw(nb, style="W", zero.policy=TRUE)

#average count for each neighbor polygon
count.lag <- lag.listw(lw, ward_boundaries_sp_2$count)

moran.test(ward_boundaries_sp_2$count,lw)

MC<- moran.mc(ward_boundaries_sp_2$count, lw, nsim=599)
MC
```



```{r}
# Problem 2
ward_boundaries_3 <- ward_boundaries

count_1 <- c(79,161,155,117,112,83,86,146,243,76)
ward_boundaries_3$count <- count_1

ward_boundaries_sp_3 <- as_Spatial(ward_boundaries_3)

#neighbors
nb <- poly2nb(ward_boundaries_sp_3, queen=TRUE)

#weights
lw <- nb2listw(nb, style="W", zero.policy=TRUE)

#average count for each neighbor polygon
count.lag <- lag.listw(lw, ward_boundaries_sp_3$count)

moran.test(ward_boundaries_sp_3$count,lw)

MC<- moran.mc(ward_boundaries_sp_3$count, lw, nsim=599)
MC
```

```{r}
# Problem 3
ward_boundaries_4 <- ward_boundaries

count_1 <- c(45,49,20,57,213,48,88,70,85,22)
ward_boundaries_4$count <- count_1

ward_boundaries_sp_4 <- as_Spatial(ward_boundaries_4)

#neighbors
nb <- poly2nb(ward_boundaries_sp_4, queen=TRUE)

#weights
lw <- nb2listw(nb, style="W", zero.policy=TRUE)

#average count for each neighbor polygon
count.lag <- lag.listw(lw, ward_boundaries_sp_4$count)

moran.test(ward_boundaries_sp_4$count,lw)

MC<- moran.mc(ward_boundaries_sp_4$count, lw, nsim=599)
MC
```
